const products = {
  design: {title:'نظام التصميم', english:'DESIGN SYSTEM',price:149,description:'مرجع واحد لشكل المنتج وسلوك مكوناته. تساعد المهارة على تحويل قرارات التصميم إلى قواعد يمكن تطبيقها ومراجعتها.',items:['تعليمات تحديد الألوان والخطوط والمسافات','قالب لمتغيرات التصميم وحالات المكونات','قائمة مراجعة للعربية وRTL وإمكانية الوصول','مثال لتسليم مواصفات المكونات إلى مطوّر الواجهة'],requirements:'تحتاج إلى موجز للمنتج ومراجع الهوية إن وجدت. تحدد الأدوات والتقنيات المختبرة عند إصدار الحزمة.',preview:'حدّد الألوان والخطوط والمسافات أولًا. استخدم مكونات مشتركة، وراجع اتجاه النص وحالات التفاعل قبل تسليم التصميم.',tags:['ألوان وخطوط','حالات المكونات','RTL']},
  frontend:{title:'تطوير الواجهات',english:'FRONTEND',price:179,description:'طريقة عمل تبدأ من فهم الصفحة وتنتهي بمراجعة تفاعل المستخدم معها، مع الالتزام بنظام التصميم المتفق عليه.',items:['تعليمات تقسيم الصفحات إلى مكونات','قالب لحالات التحميل والخطأ والبيانات الفارغة','قائمة مراجعة للشاشات الصغيرة والتنقل بلوحة المفاتيح','نموذج لربط الواجهة بعقد API واضح'],requirements:'تحتاج إلى تصميم أو مواصفات واجهة وبيئة تطوير. لا تتضمن الحزمة استضافة أو اشتراكات أدوات.',preview:'راجع نظام التصميم وعقد البيانات. نفّذ المكونات، ثم اختبر التحميل والأخطاء والتنقل على الجوال ولوحة المفاتيح.',tags:['مكونات مشتركة','شاشات صغيرة','حالات الخطأ']},
  backend:{title:'تطوير الخلفية',english:'BACKEND',price:179,description:'تعليمات لبناء منطق التطبيق وواجهاته البرمجية، وتحديد صلاحيات كل إجراء وطريقة التعامل مع المدخلات والأخطاء.',items:['قالب لتوثيق طلبات واستجابات API','تعليمات التحقق من المدخلات والصلاحيات','قائمة مراجعة لمعالجة الأخطاء والأسرار','نموذج لتسليم احتياجات البيانات إلى قسم قاعدة البيانات'],requirements:'تحتاج إلى متطلبات عمل ومخطط بيانات وبيئة تشغيل مناسبة. الأسرار ومفاتيح الخدمات تضبط خارج ملفات المهارة.',preview:'عرّف الطلبات والاستجابات قبل التنفيذ. تحقّق من البيانات والصلاحيات على الخادم، ووحّد شكل الأخطاء للواجهة.',tags:['عقود API','صلاحيات','معالجة الأخطاء']},
  database:{title:'بناء قاعدة البيانات',english:'DATABASE',price:149,description:'طريقة منظمة لتصميم البيانات ومراجعة علاقاتها، مع توثيق التغييرات قبل تطبيقها على قاعدة البيانات.',items:['تعليمات تحديد الجداول والعلاقات والقيود','قالب لتوثيق مخطط البيانات','قائمة مراجعة للفهرسة والاستعلامات','خطة لترحيل البيانات ومراجعة أثر التغييرات'],requirements:'تحتاج إلى وصف للبيانات وقاعدة بيانات ملائمة. التعديلات الحساسة تتطلب مراجعة ونسخة احتياطية قبل التطبيق.',preview:'صمّم الجداول والعلاقات بناءً على الاستخدام. وثّق القيود والفهارس، وراجع أثر الترحيل قبل تغيير البيانات.',tags:['علاقات وقيود','فهارس','ترحيل البيانات']},
  studio:{title:'حزمة الاستوديو',english:'THE STUDIO KIT',price:499,description:'التخصصات الأربعة في حزمة واحدة، مع مرجع مشترك للمشروع وطريقة واضحة لتسليم العمل بين المهارات.',items:['مهارة نظام التصميم وقوالبها','مهارة تطوير الواجهات وقوائم مراجعتها','مهارة تطوير الخلفية وعقودها','مهارة قاعدة البيانات وخطة التغييرات','دليل البداية وقالب مواصفات المشروع وتسليم العمل'],requirements:'تحتاج إلى بيئة تدعم المهارات وأدوات تنفيذ تناسب مشروعك. الحزمة لا تنشئ فريقًا مستقلًا ولا تشمل تكاليف تشغيل النماذج.'}
};
const cart = new Set();
const productDialog=document.querySelector('#product-dialog');
const cartDialog=document.querySelector('#cart-dialog');
let toastTimer;
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3000)}
function setPreview(id){const p=products[id];document.querySelectorAll('[data-preview]').forEach(btn=>{const selected=btn.dataset.preview===id;btn.setAttribute('aria-selected',String(selected));btn.tabIndex=selected?0:-1});const panel=document.querySelector('#file-panel');panel.setAttribute('aria-labelledby','tab-'+id);panel.innerHTML=`<div class="file-path mono" dir="ltr">studio / ${id==='design'?'design-system':id} / SKILL.md</div><div class="code-title" dir="ltr"># ${p.english.toLowerCase().replaceAll(' ','-')}</div><p>${p.preview}</p><div class="preview-checks">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>`}
function showProduct(id){const p=products[id];document.querySelector('#product-content').innerHTML=`<div class="dialog-eyebrow mono" dir="ltr">UDDAH / ${p.english}</div><h2 id="dialog-title">${p.title}</h2><p class="dialog-description">${p.description}</p><h3 class="dialog-label">المحتوى المقترح</h3><ul class="deliverable-list">${p.items.map(x=>`<li>${x}</li>`).join('')}</ul><div class="requirement"><strong>قبل الاستخدام</strong><br>${p.requirements}</div><div class="dialog-purchase"><span class="price"><bdi>${p.price}</bdi> <small>ر.س</small></span><button class="button primary" data-add="${id}">${cart.has(id)?'موجودة في السلة':'أضف إلى السلة'} <span aria-hidden="true">＋</span></button></div><p class="dialog-note">سعر مبدئي ضمن تصور المتجر. لا يُحصّل أي مبلغ، ولا توجد ملفات مدفوعة متاحة للتنزيل في هذه النسخة.</p>`;productDialog.showModal()}
function addToCart(id){if(cart.has(id)){showToast('هذه الحزمة موجودة في سلتك');return}if(id!=='studio'&&cart.has('studio')){showToast('المهارة مشمولة بالفعل في حزمة الاستوديو');return}if(id==='studio'){cart.clear()}cart.add(id);document.querySelector('#cart-count').textContent=cart.size;productDialog.close();renderCart();cartDialog.showModal()}
function renderCart(){const el=document.querySelector('#cart-content');if(!cart.size){el.innerHTML='<div class="cart-empty"><h3>وش يحتاج مشروعك؟</h3><p>سلتك فاضية حاليًا. شوف المهارات<br>واختر اللي يخدم شغلك.</p><button class="button primary" data-browse>تصفّح المهارات <span aria-hidden="true">←</span></button></div>';return}const sum=[...cart].reduce((a,id)=>a+products[id].price,0);el.innerHTML=`${cart.has('studio')?'<p class="bundle-conflict">حزمة الاستوديو تشمل المهارات الأربع؛ ما تحتاج تضيفها منفردة.</p>':''}${[...cart].map(id=>`<div class="cart-row"><div><h3>${products[id].title}</h3><p><bdi>${products[id].price}</bdi> ر.س · نسخة رقمية مقترحة</p></div><button class="cart-remove" data-remove="${id}" aria-label="إزالة ${products[id].title}">إزالة</button></div>`).join('')}<div class="cart-total"><span>المجموع المبدئي</span><strong><bdi>${sum}</bdi> <small>ر.س</small></strong></div><div class="demo-notice"><strong>السلة للمعاينة فقط.</strong><br>الشراء غير متاح بعد. تُعرض الأسعار النهائية والضرائب المطبقة وشروط الاستخدام والاسترجاع قبل تفعيل الدفع.</div><button class="button primary cart-return" data-browse>تابع تصفّح المهارات</button>`}
document.addEventListener('click',e=>{const detail=e.target.closest('[data-detail]');if(detail)showProduct(detail.dataset.detail);const tab=e.target.closest('[data-preview]');if(tab)setPreview(tab.dataset.preview);if(e.target.closest('[data-close]'))e.target.closest('dialog').close();const add=e.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const remove=e.target.closest('[data-remove]');if(remove){cart.delete(remove.dataset.remove);document.querySelector('#cart-count').textContent=cart.size;renderCart()}if(e.target.closest('[data-browse]')){cartDialog.close();document.querySelector('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}});
document.querySelector('#open-cart').addEventListener('click',()=>{renderCart();cartDialog.showModal()});
document.querySelector('.file-tabs').addEventListener('keydown',e=>{const buttons=[...document.querySelectorAll('[data-preview]')];let index=buttons.indexOf(document.activeElement);if(index<0)return;if(e.key==='ArrowLeft')index=(index+1)%buttons.length;else if(e.key==='ArrowRight')index=(index-1+buttons.length)%buttons.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=buttons.length-1;else return;e.preventDefault();setPreview(buttons[index].dataset.preview);buttons[index].focus()});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()}));
setPreview('design');
